"use client";

import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowRight, EnvelopeSimple, ShieldCheck } from "@phosphor-icons/react";
import { publicErrorMessage } from "@/lib/copy.mjs";

export function EmailAccessForm({ initialEmail = "", orderId, lockEmail = false, next, enabled = true }: { initialEmail?: string; orderId?: string; lockEmail?: boolean; next?: string; enabled?: boolean }) {
  const [email, setEmail] = useState(initialEmail);
  const [code, setCode] = useState("");
  const [sent, setSent] = useState(false);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [remaining, setRemaining] = useState(0);

  useEffect(() => {
    if (remaining <= 0) return;
    const timer = window.setTimeout(() => setRemaining((value) => Math.max(0, value - 1)), 1000);
    return () => window.clearTimeout(timer);
  }, [remaining]);

  async function requestCode(event?: FormEvent) {
    event?.preventDefault();
    setBusy(true); setError(null); setMessage(null);
    try {
      const response = await fetch("/api/auth/otp/request", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, orderId: lockEmail ? orderId : undefined }) });
      const payload = await response.json();
      if (payload.retryAfter) setRemaining(payload.retryAfter);
      if (!response.ok) throw new Error(payload.error ?? "Le code n’a pas pu être demandé. Réessayez plus tard.");
      setSent(true); setCode(""); setMessage(payload.message);
    } catch (requestError) { setError(publicErrorMessage(requestError, "Le code n’a pas pu être demandé. Réessayez plus tard.")); }
    finally { setBusy(false); }
  }

  async function verify(event: FormEvent) {
    event.preventDefault(); setBusy(true); setError(null);
    try {
      const response = await fetch("/api/auth/otp/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email, code, orderId, next }) });
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.error ?? "Le code n’a pas pu être vérifié.");
      // The destination is generated by the server from an owned purchase.
      if (typeof payload.next !== "string" || !payload.next.startsWith("/") || payload.next.startsWith("//")) throw new Error("Vos achats n’ont pas pu être ouverts.");
      window.location.assign(payload.next);
    } catch (verifyError) { setError(publicErrorMessage(verifyError, "Le code n’a pas pu être vérifié.")); setBusy(false); }
  }

  if (!enabled) return <div className="email-access-form"><p role="status">La connexion par e-mail est temporairement indisponible.</p><Link className="text-link" href="/connexion?next=%2Fbibliotheque">Se connecter avec un mot de passe</Link></div>;
  return <div className="email-access-form">
    <p className="email-access-intro"><ShieldCheck size={18} aria-hidden="true" /> Un code personnel protège l’accès à vos achats.</p>
    <form className="form-stack" onSubmit={sent ? verify : requestCode}>
      <div className="field-group"><label htmlFor="access-email">Adresse e-mail de l’achat</label><input className="field-input" id="access-email" type="email" autoComplete="email" required maxLength={254} readOnly={lockEmail || sent} value={email} onChange={(event) => setEmail(event.target.value)} placeholder="vous@exemple.com" /></div>
      {sent && <div className="field-group"><label htmlFor="access-code">Code reçu par e-mail</label><input className="field-input otp-input" id="access-code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6,8}" minLength={6} maxLength={8} required value={code} onChange={(event) => setCode(event.target.value.replace(/\D/g, ""))} placeholder="Votre code" /><span className="field-help">Le code est valable dix minutes. Vérifiez aussi vos courriers indésirables.</span></div>}
      {error && <p className="form-error" role="alert">{error}</p>}
      {message && <p className="field-help" role="status">{message}</p>}
      <button className="button button-dark" type="submit" disabled={busy || (!sent && remaining > 0)}>{busy ? sent ? "Vérification…" : "Demande du code…" : sent ? "Accéder à mes achats" : "Recevoir mon code"}{sent ? <ArrowRight size={17} /> : <EnvelopeSimple size={17} />}</button>
      {sent && <button className="text-link" type="button" disabled={busy || remaining > 0} onClick={() => void requestCode()}>{remaining > 0 ? `Renvoyer le code dans ${remaining} s` : "Renvoyer le code"}</button>}
      {sent && !lockEmail && <button className="text-link" type="button" disabled={busy} onClick={() => { setSent(false); setCode(""); setMessage(null); setError(null); }}>Changer d’adresse e-mail</button>}
      <p className="field-help">Si vous n’avez pas encore de compte, la validation du code active votre espace acheteur sans mot de passe.</p>
    </form>
    {lockEmail && <p className="field-help">Une erreur dans votre adresse après paiement ? Contactez Sellow avec la référence de votre commande pour demander une correction.</p>}
    <Link className="text-link" href="/connexion?next=%2Fbibliotheque">Utiliser mon mot de passe</Link>
  </div>;
}
