import type { Creator, Product } from "@/lib/types";

export const seedCreators: Creator[] = [
  {
    id: "creator-ines",
    name: "Inès Laurent",
    slug: "ines-laurent",
    email: "ines@example.test",
    bio: "Directrice artistique à Lyon. Je crée des outils simples pour les identités qui ont quelque chose à raconter.",
    initials: "IL",
    tone: "rose",
  },
  {
    id: "creator-malik",
    name: "Malik Diallo",
    slug: "malik-diallo",
    email: "malik@example.test",
    bio: "Photographe et formateur. Je partage les méthodes qui rendent une image plus vivante.",
    initials: "MD",
    tone: "blue",
  },
  {
    id: "creator-clara",
    name: "Clara Nsimba",
    slug: "clara-nsimba",
    email: "clara@example.test",
    bio: "Illustratrice indépendante. Des carnets, des ateliers et des objets imprimés en petites séries.",
    initials: "CN",
    tone: "yellow",
  },
  {
    id: "creator-noe",
    name: "Noé Bernard",
    slug: "noe-bernard",
    email: "noe@example.test",
    bio: "Développeur créatif. J’aide les petites équipes à transformer une idée en outil utile.",
    initials: "NB",
    tone: "green",
  },
];

const today = "2026-09-28T10:00:00.000Z";

export const seedProducts: Product[] = [
  {
    id: "seed-kit-marque",
    slug: "kit-identite-vivante",
    title: "Le kit d’identité vivante",
    subtitle: "Un système de marque prêt à faire grandir.",
    description:
      "Une collection de grilles, de palettes et de modèles Figma pour créer une identité cohérente sans perdre ce qui la rend singulière.",
    kind: "download",
    category: "Design",
    tags: ["figma", "identité", "modèles"],
    price: 24,
    currency: "EUR",
    creatorId: "creator-ines",
    creatorName: "Inès Laurent",
    creatorSlug: "ines-laurent",
    creatorInitials: "IL",
    creatorTone: "rose",
    cover: "identity",
    coverLabel: "UNE IDENTITÉ\nEN MOUVEMENT",
    fileName: "kit-identite-vivante.zip",
    published: true,
    createdAt: today,
    featured: true,
  },
  {
    id: "seed-photo",
    slug: "photo-produit-naturelle",
    title: "Photo produit naturelle",
    subtitle: "La lumière du jour comme premier studio.",
    description:
      "Un guide pratique pour photographier vos produits avec la lumière disponible, quelques surfaces et un téléphone.",
    kind: "course",
    category: "Photographie",
    tags: ["photo", "lumière", "création"],
    price: 32,
    currency: "EUR",
    creatorId: "creator-malik",
    creatorName: "Malik Diallo",
    creatorSlug: "malik-diallo",
    creatorInitials: "MD",
    creatorTone: "blue",
    cover: "photography",
    coverLabel: "LUMIÈRE\nDE JOUR",
    published: true,
    createdAt: today,
    featured: true,
    details: {
      lessons: 3,
      duration: "54 min",
      courseLessons: [
        { id: "photo-01", title: "Observer la lumière", description: "Repérez les zones de lumière naturelle et choisissez un fond simple.", durationMinutes: 12, videoUrl: "https://www.youtube.com/watch?v=qy4I7y77gTE", isPreview: true },
        { id: "photo-02", title: "Composer une scène", description: "Placez votre produit et quelques accessoires sans surcharger l’image.", durationMinutes: 18 },
        { id: "photo-03", title: "Faire ses premières retouches", description: "Ajustez l’exposition et les couleurs en gardant un rendu naturel.", durationMinutes: 24 },
      ],
    },
  },
  {
    id: "seed-carnet",
    slug: "carnet-des-petites-idees",
    title: "Le carnet des petites idées",
    subtitle: "Faire de la place aux projets qui commencent.",
    description:
      "Un carnet imprimé pour noter, relier et faire mûrir les idées qui méritent un peu plus d’attention.",
    kind: "physical",
    category: "Papeterie",
    tags: ["carnet", "illustration", "papier"],
    price: 19,
    currency: "EUR",
    creatorId: "creator-clara",
    creatorName: "Clara Nsimba",
    creatorSlug: "clara-nsimba",
    creatorInitials: "CN",
    creatorTone: "yellow",
    cover: "notebook",
    coverLabel: "IDÉES\nEN COURS",
    published: true,
    createdAt: today,
    featured: true,
    details: { shipping: "Expédition sous 3 jours ouvrés" },
  },
  {
    id: "seed-figma",
    slug: "figma-du-croquis-au-prototype",
    title: "Figma, du croquis au prototype",
    subtitle: "Concevoir une interface claire, étape par étape.",
    description:
      "Un cours pour passer d’une première idée à un prototype testable, avec une méthode que vous pourrez réutiliser sur vos projets.",
    kind: "course",
    category: "Design",
    tags: ["figma", "interface", "prototype"],
    price: 46,
    currency: "EUR",
    creatorId: "creator-ines",
    creatorName: "Inès Laurent",
    creatorSlug: "ines-laurent",
    creatorInitials: "IL",
    creatorTone: "rose",
    cover: "prototype",
    coverLabel: "DU CROQUIS\nAU PROTOTYPE",
    published: true,
    createdAt: today,
    details: { lessons: 12, duration: "2 h 18" },
  },
  {
    id: "seed-newsletter",
    slug: "atelier-du-dimanche",
    title: "L’atelier du dimanche",
    subtitle: "Une lettre créative pour ralentir et fabriquer.",
    description:
      "Chaque mois, retrouvez une nouvelle proposition créative, des références choisies et un petit exercice à faire à votre rythme.",
    kind: "membership",
    category: "Illustration",
    tags: ["newsletter", "atelier", "communauté"],
    price: 8,
    currency: "EUR",
    creatorId: "creator-clara",
    creatorName: "Clara Nsimba",
    creatorSlug: "clara-nsimba",
    creatorInitials: "CN",
    creatorTone: "yellow",
    cover: "membership",
    coverLabel: "UN DIMANCHE\nÀ SOI",
    published: true,
    createdAt: today,
    details: {
      interval: "mois",
      membershipPosts: [
        { id: "atelier-01", title: "Une idée pour le prochain dimanche", body: "Choisissez trois objets autour de vous et dessinez les formes qui vous attirent. Gardez la première version, même imparfaite.", createdAt: "2026-09-28T09:00:00.000Z" },
        { id: "atelier-02", title: "Des couleurs qui se répondent", body: "Commencez avec une couleur que vous aimez. Cherchez ensuite une teinte qui l’apaise et une autre qui la réveille.", createdAt: "2026-09-14T09:00:00.000Z" },
      ],
    },
  },
  {
    id: "seed-starter",
    slug: "starter-kit-site-vitrine",
    title: "Starter kit pour site vitrine",
    subtitle: "Une base rapide pour publier votre prochain projet.",
    description:
      "Une base de composants et de pages prêtes à adapter pour lancer un site vitrine simple et soigné.",
    kind: "download",
    category: "Développement",
    tags: ["code", "site", "starter kit"],
    price: 28,
    currency: "EUR",
    creatorId: "creator-noe",
    creatorName: "Noé Bernard",
    creatorSlug: "noe-bernard",
    creatorInitials: "NB",
    creatorTone: "green",
    cover: "website",
    coverLabel: "PRÊT À\nPUBLIER",
    fileName: "site-vitrine-starter.zip",
    published: true,
    createdAt: today,
    featured: true,
  },
  {
    id: "seed-portfolio",
    slug: "portfolio-qui-raconte",
    title: "Un portfolio qui raconte",
    subtitle: "Clarifier votre travail avant de le montrer.",
    description:
      "Une session individuelle pour choisir vos projets, poser votre fil conducteur et construire une présentation qui vous ressemble.",
    kind: "service",
    category: "Créativité",
    tags: ["portfolio", "conseil", "indépendant"],
    price: 75,
    currency: "EUR",
    creatorId: "creator-ines",
    creatorName: "Inès Laurent",
    creatorSlug: "ines-laurent",
    creatorInitials: "IL",
    creatorTone: "rose",
    cover: "portfolio",
    coverLabel: "VOTRE TRAVAIL\nA SA PLACE",
    published: true,
    createdAt: today,
    details: { fulfillment: "Une séance de 45 minutes en visio" },
  },
  {
    id: "seed-audio",
    slug: "sons-du-matin",
    title: "Sons du matin",
    subtitle: "Une bibliothèque de sons pour vos films.",
    description:
      "Des ambiances enregistrées dans des lieux calmes, prêtes à glisser dans vos montages, podcasts et films courts.",
    kind: "download",
    category: "Musique",
    tags: ["audio", "sons", "montage"],
    price: 16,
    currency: "EUR",
    creatorId: "creator-malik",
    creatorName: "Malik Diallo",
    creatorSlug: "malik-diallo",
    creatorInitials: "MD",
    creatorTone: "blue",
    cover: "audio",
    coverLabel: "ÉCOUTER\nLE CALME",
    fileName: "sons-du-matin.zip",
    published: true,
    createdAt: today,
  },
  {
    id: "seed-palette",
    slug: "palette-des-jours-chauds",
    title: "La palette des jours chauds",
    subtitle: "Des couleurs à garder sous la main.",
    description:
      "Des palettes, textures et petits motifs scannés pour donner à vos projets une note plus personnelle.",
    kind: "download",
    category: "Illustration",
    tags: ["couleur", "textures", "illustration"],
    price: 12,
    currency: "EUR",
    creatorId: "creator-clara",
    creatorName: "Clara Nsimba",
    creatorSlug: "clara-nsimba",
    creatorInitials: "CN",
    creatorTone: "yellow",
    cover: "palette",
    coverLabel: "DES COULEURS\nQUI RESTENT",
    fileName: "palette-jours-chauds.zip",
    published: true,
    createdAt: today,
  },
  {
    id: "seed-no-code",
    slug: "automatiser-sans-se-compliquer",
    title: "Automatiser sans se compliquer",
    subtitle: "Relier vos outils sans écrire une ligne de code.",
    description:
      "Un atelier vidéo pour repérer les tâches répétitives et assembler des automatisations faciles à maintenir.",
    kind: "course",
    category: "Développement",
    tags: ["automatisation", "atelier", "outils"],
    price: 38,
    currency: "EUR",
    creatorId: "creator-noe",
    creatorName: "Noé Bernard",
    creatorSlug: "noe-bernard",
    creatorInitials: "NB",
    creatorTone: "green",
    cover: "flow",
    coverLabel: "MOINS DE TÂCHES\nEN BOUCLE",
    published: true,
    createdAt: today,
    details: { lessons: 9, duration: "1 h 25" },
  },
];
